Web.TaskManagementSystem/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using Web.TaskManagementSystem.ViewModels;
using Web.TaskManagementSystem.Services;
using System.Linq;
using System.Web.Mvc;
using Controller = Microsoft.AspNetCore.Mvc.Controller;

namespace Web.TaskManagementSystem.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ICategoryService<CategoryViewModel> _categoryService;

        public CategoryController(ICategoryService<CategoryViewModel> categoryService)
        {
            _categoryService = categoryService;
        }

        public IActionResult List()
        {
            var categories = _categoryService.List();
            return View(categories);
        }

        public IActionResult Details(int id)
        {
            var category = _categoryService.Get(id);
            return View(category);
        }

        public IActionResult Update(int id)
        {
            var category = _categoryService.Get(id);
            return View(category);
        }

        public IActionResult Edit(CategoryViewModel category)
        {
            _categoryService.Update(category);
            return RedirectToAction(Constants.Route.List, Constants.Route.Category);
        }

        public IActionResult Create()
        {
            if (_categoryService.CanCreate())
            {
                return View(new CategoryViewModel { });
            }
            return RedirectToAction(Constants.Route.Account, Constants.Route.User);
        }

        public IActionResult Insert(CategoryViewModel category)
        {
            _categoryService.Create(category);
            return RedirectToAction(Constants.Route.List, Constants.Route.Category);
        }

        public IActionResult Delete(int id)
        {
            if (_categoryService.IsDeleted(id))
            {
                return RedirectToAction(Constants.Route.List, Constants.Route.Category);
            }
            return RedirectToAction(Constants.Route.Account, Constants.Route.User);
        }
    }
}

Web.TaskManagementSystem/Controllers/CommentController.cs
using Microsoft.AspNetCore.Mvc;
using Web.TaskManagementSystem.ViewModels;
using Web.TaskManagementSystem.Services;
namespace Web.TaskManagementSystem.Controllers
{
    public class CommentController : Controller
    {
        private readonly ICommentService<CommentViewModel> _commentService;
        private readonly ITaskService<TaskViewModel> _taskService;
        private readonly IUserService<UserViewModel> _userService;
        public CommentController(ICommentService<CommentViewModel> commentService, ITaskService<TaskViewModel> taskService, IUserService<UserViewModel> userService)
        {
            _commentService = commentService;
            _taskService = taskService;
            _userService = userService;
        }

        public IActionResult List()
        {
            var comments = _commentService.List();
            return View(comments);
        }

        public IActionResult Details(int id)
        {
            var comment = _commentService.Get(id);
            return View(comment);
        }

        public IActionResult Update(int id)
        {
            var comment = _commentService.Get(id);
            comment.Users = _userService.List();
            comment.Tasks = _taskService.List();
            return View(comment);
        }

        public IActionResult Edit(CommentViewModel comment)
        {
            _commentService.Update(comment);
            return RedirectToAction(Constants.Route.List, Constants.Route.Comment);
        }

        public IActionResult Create()
        {
            if (_commentService.CanCreate())
            {
                var vm = new CommentViewModel
                {
                    Users = _userService.List(),
                    Tasks = _taskService.List()
                };
                return View(vm);
            }
            return RedirectToAction(Constants.Route.Account, Constants.Route.User);
        }

        public IActionResult Insert(CommentViewModel category)
        {
            _commentService.Create(category);
            return RedirectToAction(Constants.Route.List, Constants.Route.Comment);
        }

        public IActionResult Delete(int id)
        {
            if (_commentService.IsDeleted(id))
            {
                return RedirectToAction(Constants.Route.List, Constants.Route.Comment);
            }
            return RedirectToAction(Constants.Route.Account, Constants.Route.User);
        }
    }
}

Web.TaskManagementSystem/Controllers/TaskController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using Web.TaskManagementSystem.Services;
using Web.TaskManagementSystem.ViewModels;

namespace Web.TaskManagementSystem.Controllers
{
    public class TaskController : Controller
    {
        private readonly ITaskService<TaskViewModel> _taskService;
        private readonly ICategoryService<CategoryViewModel> _categoryService;
        private readonly IUserService<UserViewModel> _userService;

        public TaskController(ITaskService<TaskViewModel> taskService, ICategoryService<CategoryViewModel> categoryService, IUserService<UserViewModel> userService)
        {
            _taskService = taskService;
            _categoryService = categoryService;
            _userService = userService;
        }

        public IActionResult List(FilterTaskViewModel filter)
        {
            var model = new FilterTaskViewModel();
            var tasks = new List<TaskViewModel>();
            if (filter.Task != null)
            {
                tasks = _taskService.Search(filter);
            }
            else
            {
                tasks = _taskService.List();
            }
            model.Tasks = tasks;
            return View(model);
        }

        public ActionResult Details(int id)
        {
            var task = _taskService.Get(id);
            return View(task);
        }

        public IActionResult Update(int id)
        {
            var task = _taskService.Get(id);
            task.Categories = _categoryService.List();
            task.Users = _userService.List();
            return View(task);
        }

        public IActionResult Edit(TaskViewModel task)
        {
            _taskService.Update(task);
            return RedirectToAction(Constants.Route.List, Constants.Route.Task);
        }

        public IActionResult Create()
        {
            if (_taskService.CanCreate())
            {
                var vm = new TaskViewModel
                {
                    Categories = _categoryService.List(),
                    Users = _userService.List()
                };
                return View(vm);
            }
            return RedirectToAction(Constants.Route.Account, Constants.Route.User);
        }

        public IActionResult Insert(TaskViewModel task)
        {
            _taskService.Create(task);
            return RedirectToAction(Constants.Route.List, Constants.Route.Task);
        }

        public IActionResult Delete(int id)
        {
            if (_taskService.IsDeleted(id))
            {
                return RedirectToAction(Constants.Route.List, Constants.Route.Task);
            }
            return RedirectToAction(Constants.Route.Account, Constants.Route.User);
        }
    }
}

Web.TaskManagementSystem/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;
﻿
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Task Management System</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="icon" href="https://cdn3.iconfinder.com/data/icons/communication-1-2/256/Team-512.png" />
</head>
<body>

    <header>
        <nav class="navbar fixed-top navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="https://freeiconshop.com/wp-content/uploads/edd/task-done-flat.png" width="30" height="30"> <label class="text-white">Task Management System</label>
                </a>

                <!-- Centered link -->
                <div class="topnav-centered">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Task" asp-action="List">Tasks</a>
                        </li>
                        @if (@Context.Session.GetString("Role") == "Admin")
                        {

                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Category" asp-action="List">Category</a>
                            </li>
                        }
                        @if (@Context.Session.GetString("Role") == "Admin")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="User" asp-action="List">User</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Comment" asp-action="List">Comment</a>
                            </li>
                        }
                    </ul>

                </div>
                <div>
                    <ul class="navbar-nav flex-grow-1 ">
                        @if (@Context.Session.GetString("IsStateLogged") != "true")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="User" asp-action="Account">Account</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="User" asp-action="Profile">Profile</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="User" asp-action="SignOut">Sign Out</a>
                            </li>
                        }
                    </ul>
                        <ul class="navbar-nav flex-grow-1">

        <li class="nav-item ">


            <div class="btn-group ">


                <div class="dropdown-menu">
                    @if (@Context.Session.GetString("IsStateLogged") != "true")
                    {
                        <a class="nav-item" asp-area="" asp-controller="User" asp-action="SignIn">Log in</a>

                        <a class="nav-item" asp-area="" asp-controller="User" asp-action="SignUp">Register</a>
                    }
                    @if (@Context.Session.GetString("IsStateLogged") == "true")
                    {
                        <a class="nav-item" asp-area="" asp-controller="User" asp-action="Profile">Profile</a>

                        <a class="nav-item" asp-area="" asp-controller="User" asp-action="SignOut">Sign Out</a>
                    }
                </div>
            </div>


                    </li>
                    </ul>
                </div>
</div>
        </nav>
    </header>
    <div class="container body-content">
        <br /> <br /><br /><br />
        @RenderBody()
        <br />
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Task Management System</p>
        </footer>
    </div>
    @*cripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")*@
    @RenderSection("scripts", required: false)
</body>
</html>